export const LOAD_BLOCKCHAIN = "LOAD_BLOCKCHAIN";
export const BLOCKCHAIN_ERROR = "BLOCKCHAIN_ERROR";
export const LOAD_USER = "LOAD_USER";
export const LOAD_USER_ERROR = "LOAD_USER_ERROR";
export const LOAD_WALLET_ADDRESS = "LOAD_WALLET_ADDRESS";
export const LOAD_TOTAL_SUPPLY = "LOAD_TOTAL_SUPPLY";
export const WRONG_NETWORK = "WRONG_NETWORK";
